make initialConfiguracao:
	curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
	sudo apt install nodejs
	sudo apt update
	sudo npm install --global expo-cli
	sudo npm install -g npm@8.16.0
make createProject:
	expo init hackathonalfa
make run:
	expo start
make installDependencies:
	npm install